all:
  hosts:
    openclaw_host:
      ansible_host: "zeroklaw-host"
      vars:
        ansible_user: "{{ host_user }}"

    openclaw_vm:
      ansible_host: "zeroklaw-vm"
      vars:
        ansible_user: "{{ vm_vm_user }}"
