---
- name: Run source install
  ansible.builtin.shell: "curl -fsSL https://deb.nodesource.com/setup_24.x | bash -"
  become: true

- name: Install nodejs
  become: true
  ansible.builtin.apt:
    package:
      - nodejs
    state: present
    update_cache: true