---
- name: Include user tasks
  ansible.builtin.import_tasks: user.yml
  tags: [never, user]

- name: Include SSH hardening tasks
  ansible.builtin.import_tasks: ssh_hardening.yml
  tags: [never, ssh_hardening]

- name: Include nftables tasks
  ansible.builtin.import_tasks: nftables.yml
  tags: [never, nftables]

- name: Include Tailscale tasks
  ansible.builtin.import_tasks: tailscale.yml
  tags: [never, tailscale]

- name: Include Promtail tasks
  ansible.builtin.import_tasks: promtail.yml
  tags: [never, promtail]

- name: Include libvirt tasks
  ansible.builtin.import_tasks: libvirt.yml
  tags: [never, libvirt]